apiVersion: v1
kind: Namespace
metadata:
  name: mspr-bloc2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mspr-bloc2-frontend
  namespace: mspr-bloc2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mspr-bloc2-frontend
  template:
    metadata:
      labels:
        app: mspr-bloc2-frontend
    spec:
      containers:
        - name: mspr-bloc2-frontend
          image: ghcr.io/jul-fls/mspr-bloc2-cofrap/front:${GIT_COMMIT_SHA}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # livenessProbe:
          #   httpGet:
          #     path: /status/200
          #     port: 80
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mspr-bloc2-frontend
  namespace: mspr-bloc2
spec:
  type: NodePort
  selector:
    app: mspr-bloc2-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32600